SET(LIBSSH2_ROOT_DIR "" CACHE PATH "The libssh2 root directory")

SET(LIBSSH2_REGKEY "[HKEY_LOCAL_MACHINE\\SOFTWARE\\libssh2;InstallPath]")

FIND_PATH(LIBSSH2_INCLUDE
    libssh2.h
    PATHS ${LIBSSH2_REGKEY}/include
    HINTS ${LIBSSH2_ROOT_DIR}/include
)

FIND_LIBRARY(LIBSSH2_LIBRARY
    ssh2
    PATHS ${LIBSSH2_REGKEY}/lib
    HINTS ${LIBSSH2_ROOT_DIR}/lib
)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(Libssh2 DEFAULT_MSG LIBSSH2_LIBRARY LIBSSH2_INCLUDE)

IF(LIBSSH2_FOUND)
    SET(LIBSSH2_LIBRARIES ${LIBSSH2_LIBRARY})
    SET(LIBSSH2_INCLUDE_DIRS ${LIBSSH2_INCLUDE})
ENDIF(LIBSSH2_FOUND)
